# [START runtime]
service: default
runtime: nodejs
env: flex
# [END runtime]

env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: gcp2@cloud
  MYSQL_DATABASE: prodcat
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: bill-hahn-sandbox:us-central1:myinstance
  
